name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build Release
    runs-on: windows-latest
    timeout-minutes: 30
     
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Init Cargo cache
      uses: Swatinem/rust-cache@v2

    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build Windows x64
      run: cargo build --release

    - name: Build Linux x64
      run: cross build --release --target x86_64-unknown-linux-musl

    - name: list all files
      run: find . -type f
      
    - name: Move and strip libraries
      run: mv target/release/libdynops.so dynops_x64.so
  
    - name: Install HEMTT
      uses: arma-actions/hemtt@main

    - name: Run HEMTT build
      run: hemtt release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: addon
        path: releases/dynops-latest.zip
        if-no-files-found: error
